app:
  image: https://ec2-52-89-6-176.us-west-2.compute.amazonaws.com/docker-demo:latest
  entrypoint: /bin/bash
  command: -c "sleep 5 && go-wrapper run" # sleep because the postgres container isn't ready on first start
  environment:
    - "TITLE=Docker Demo"
    - "DB_USER=demo"
    - "DB_PASS=demo"
    - "DB_NAME=demo"
    - "DB_SSL_MODE=disable"
  links:
    - "db:db"
  ports:
    - 8080:8080
  expose:
    - 8080

db:
  image: postgres:latest
  environment:
    - "POSTGRES_USER=demo"
    - "POSTGRES_PASSWORD=demo"
  expose:
    - 5432
